language: python
python: 3.7
if: branch = master or tag IS present
os: linux
services: docker

before_script:
  - echo "$QUAY_PASSWORD" | sudo docker login -u "$QUAY_USERNAME" --password-stdin quay.io

jobs:
  include:
    - stage: Test build
      if: tag IS not present
      script: make build TAG=dev

    - stage: Release
      if: tag IS present
      script: make build push TAG=$TRAVIS_TAG
